#!/usr/bin/env bash
# Extracts the fork's virtual-display / client-display-selection delta as per-file patches in the
# direction it is needed for the re-fork lane:  upstream/master -> linux-support.
# The patch set is the mechanical half of the port queue (docs/fork-linux-port-queue.md); the
# capability/permission traps are already re-applied in the branch history.
set -uo pipefail
cd "$(dirname "$0")/.."
FORK=${FORK:-linux-support}
UP=${UP:-upstream/master}
OUT=docs/reapply-vdisplay
rm -rf "$OUT"
mkdir -p "$OUT"

mapfile -t PATHS <<'EOF'
src/platform/linux/misc.cpp
src/platform/linux/misc.h
src/platform/linux/kwingrab.cpp
src/platform/linux/display_device.cpp
src/platform/linux/display_device/session_listener.cpp
src/platform/linux/display_device/session_listener.h
src/platform/common.h
src/video.cpp
src/rtsp.cpp
src/nvhttp.cpp
src/nvhttp/display_control.cpp
src/nvhttp/display_control.h
src/nvhttp_stream_start.cpp
src/process.cpp
src/display_device/parsed_config.cpp
src/display_device/parsed_config.h
src/display_device/display_device.h
src/config.cpp
src/config.h
cmake/compile_definitions/linux.cmake
EOF

# 1) write the patches
: > /tmp/fsl-reapply-sizes.tsv
for p in "${PATHS[@]}"; do
  upstream_has=no
  git cat-file -e "$UP:$p" 2>/dev/null && upstream_has=yes
  name=$(echo "$p" | tr '/' '_')
  tmp=$(mktemp)
  git diff "$UP" "$FORK" -- "$p" > "$tmp"
  if [ -s "$tmp" ]; then
    mv "$tmp" "$OUT/$name.patch"
    printf '%s\t%s\t%s\n' "$name.patch" "$(wc -l < "$OUT/$name.patch")" "$upstream_has" >> /tmp/fsl-reapply-sizes.tsv
  else
    rm -f "$tmp"
    printf '%s\t0\t%s\n' "$name.patch" "$upstream_has" >> /tmp/fsl-reapply-sizes.tsv
  fi
done

# 2) write the README
{
cat <<'EOF'
# Re-apply patches — virtual display / client display selection

Generated by `scripts/gen-vdisplay-reapply-patches.sh`. Each patch is the fork's delta for one file
in the direction `upstream/master -> linux-support`, i.e. what has to be re-applied on top of the
upstream base (`refork/linux`).

**How to read them.** They are whole-file deltas and mix two things:

- **our feature** — the virtual-display / client-display-selection hunks;
- **AlkaidLab's shared-core rewrite** — in `common.h`, `video.cpp`, `rtsp.cpp`, `nvhttp.cpp`,
  `process.cpp`, `config.*` and `cmake/compile_definitions/linux.cmake` most of the diff is theirs
  (Windows features, the nvhttp module split). Those are **reference material, not appliable
  patches** — locate our hunks with e.g.
  `grep -n 'SUNSHINE_CLIENT_DISPLAY_NAME\|client_display_names\|VDISPLAY_\|resolve_display_intent' <patch>`.
- **fork-only files** (`display_control.*`, `nvhttp_stream_start.cpp`, `parsed_config.*`,
  `display_device.h`, `platform/linux/display_device.cpp`, `session_listener.*`) have no upstream
  counterpart: the patch creates the file, so treat it as source to adapt rather than something to
  replay.

**Order** (dependencies first; each step must build before the next lands):

1. `src_platform_linux_misc_h.patch`, `src_platform_linux_misc_cpp.patch` — client display list
   (`client_display_names()`), virtual-id constants, per-session source re-verification.
2. `src_platform_common_h.patch` — declarations. The capability-helper half is already in the
   branch (commit "re-apply the three upstream-side cap/probe traps").
3. `src_platform_linux_kwingrab_cpp.patch` — KWin output enumeration/streaming changes.
4. `src_platform_linux_display_device*.patch` — Linux display enumeration for client validation;
   on upstream it belongs next to `display_names()` (upstream has no `display_device::` intent layer).
5. `src_nvhttp_display_control*.patch` + the `/displays` route in `src_nvhttp_cpp.patch`.
6. `src_video_cpp.patch`, `src_rtsp_cpp.patch`, `src_config*.patch` — per-session display pick:
   `display_name` launch argument → session env → `monitor.display_name` → resolution/validation in
   `video.cpp`, including the 20 s wait for a hook-created output.
7. `src_process_cpp.patch` — export `SUNSHINE_CLIENT_*` into the prep-hook child environment and
   erase per-session keys.
8. `src_nvhttp_stream_start_cpp.patch` — run the do-hook before the encoder probe on a virtual pick.
9. `src_display_device_parsed_config*.patch`, `src_display_device_display_device_h.patch` — intent
   translation/validation. **Redesign required**: upstream has no intent concept; express it
   against upstream's display handling.

> Do not advertise the virtual ids (steps 1/5) before step 6 lands: a client that can pick
> `虚拟-KWin` while the launch path cannot honour it gets a hard 503 instead of a working stream
> (the skill's no-regression rule). Gate the offer behind a compile-time constant if the two steps
> cannot land together.

## Patch sizes

| patch | lines | upstream counterpart |
|---|---|---|
EOF
while IFS=$'\t' read -r name lines has; do
  printf '| `%s` | %s | %s |\n' "$name" "$lines" "$([ "$has" = yes ] && echo yes || echo 'no (fork-only)')"
done < /tmp/fsl-reapply-sizes.tsv
} > "$OUT/README.md"
echo "wrote $OUT/README.md ($(ls "$OUT"/*.patch | wc -l) patches)"
