#!/usr/bin/env bash
# Regenerates docs/upstream-linux-commits.md: every LizardByte/Sunshine commit that
# touches the Linux runtime paths, since this fork's upstream base (34054a20, 2024-08-26).
# Status annotations are maintained in the case block below — keep them honest.
set -uo pipefail
cd "$(dirname "$0")/.."
BASE=34054a20
UP=upstream/master
OUT=docs/upstream-linux-commits.md

annotate() {
  case "$1" in
    # --- ported on this fork's linux-support branch ---
    c553565b) echo "**ported** (env sanitizer; the privileged-DRM-worker half is intentionally left out)" ;;
    502be646) echo "**ported**" ;;
    e5759171) echo "**ported**" ;;
    f273ce8f|22310da7|8c74826f|3745a359) echo "**ported** (adapted to this fork's framerateX100 pacing)" ;;
    40ae6c80) echo "**ported**" ;;
    7a30ead4) echo "**ported**" ;;
    a4c253f3) echo "**ported** (typo)" ;;
    # --- already present in this fork (AlkaidLab forward-port or our backport) ---
    4e6e1377|2438a9bd) echo "already present (pipewire object serial)" ;;
    bba6c6ca) echo "already present (framerateX100)" ;;
    a90d3068) echo "already present (kwin backport, PR #5009)" ;;
    ecba5c3c|e39dfb80) echo "already present" ;;
    a682ab07) echo "already present (fork variant)" ;;
    39c9e845|e4740f06) echo "already present (AlkaidLab's own yuv444 work)" ;;
    017ce496) echo "already present (fork HDR handling)" ;;
    # --- assessed: does not apply here ---
    38a94b3c) echo "rejected: single-GPU NVIDIA host — would remove VAAPI capture for nvidia-vaapi-driver users" ;;
    cf7b0dc7) echo "n/a: this fork's wayland.cpp does not use wlr-screencopy copy" ;;
    9051ae84) echo "n/a: no active_av1_mode/active_hevc_mode block in this fork" ;;
    d64016a4) echo "n/a without the privileged DRM worker" ;;
    a9038852) echo "n/a: this fork does not build vulkan_encode.cpp" ;;
    9e1f089e) echo "n/a: this fork has no platf::set_thread_name" ;;
    # --- assessed: real work, still pending ---
    3cba9bae|4b745485|a55d2d99) echo "pending: KMS display naming rework; must be coordinated with the fork's display_device enumeration" ;;
    fb925302) echo "pending: needs the wayland.cpp forward-port (2026 planner)" ;;
    cb72dffa|6ad5f973|33aaefa8|7a4c940e|0e66dd81) echo "pending: needs the 2026 pipewire.cpp refactor" ;;
    7a987eec) echo "pending: privileged EGL worker architecture (goes with c553565b)" ;;
    1d9ab7b8) echo "candidate: needs platf::resolve_render_device()" ;;
    71acfc57) echo "candidate: VAAPI encoder options (orthogonal on a CUDA host)" ;;
    2ebaae37) echo "pending: touches 2026 wlgrab/wayland.h; the Nix build always has CUDA" ;;
    3dfbfe09|aca5d23f|c9bcee44|c3138518|293c1ed3|76c3463d|c2b5513a|a241c78c|d14ccf25|b43a9b8e) echo "pending: needs the wayland/wlgrab forward-port" ;;
  esac
}

{
  cat <<EOF
# LizardByte/Sunshine Linux commits since the fork base

Generated by \`scripts/gen-upstream-linux-inventory.sh\` — do not edit by hand.
Fork base: \`$BASE\` (2024-08-26). Upstream audited at: \`$(git rev-parse --short $UP)\`.

This is the complete work list for "bring LizardByte's Linux changes into this fork".
An empty status means the commit has not been evaluated yet; every non-empty status is a
claim that was checked against this tree (build-verified for the *ported* rows).

EOF
  for y in 2024 2025 2026; do
    echo "## $y"
    echo
    echo "| commit | date | subject | status |"
    echo "|---|---|---|---|"
    git log --reverse --format='%h|%ad|%s' --date=short --since=$y-01-01 --until=$((y + 1))-01-01 \
      $BASE..$UP -- src/platform/linux src/video.cpp src/display_device packaging/linux cmake/packaging/linux.cmake |
      while IFS='|' read -r c d s; do
        printf '| `%s` | %s | %s | %s |\n' "$c" "$d" "$(echo "$s" | sed 's/|/\\|/g')" "$(annotate "$c")"
      done
    echo
  done
  echo "Total: $(git rev-list --count $BASE..$UP -- src/platform/linux src/video.cpp src/display_device packaging/linux cmake/packaging/linux.cmake) commits."
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
