#!/usr/bin/env bash
# Regenerates docs/fork-linux-port-queue.md: every fork commit authored by Biaogo that touches
# the Linux-relevant surface, classified for the re-fork lane (branch refork/linux, based on
# LizardByte/Sunshine upstream/master). Classification is maintained in the case block below —
# keep it honest: "re-apply" means the capability must be re-implemented on the upstream base,
# "skip" means the base already contains it or it only exists to work around the fork's core.
set -uo pipefail
cd "$(dirname "$0")/.."
BASE=34054a20
FORK=linux-support
UP=upstream/master
OUT=docs/fork-linux-port-queue.md

classify() {
  case "$1" in
    # --- drop: upstream is the origin of the capability (the fork backported it in 2026-09) ---
    54f1ce99) echo "drop — upstream PR #5009 is the origin of KWin ScreenCast capture" ;;
    1a343f28) echo "drop — upstream already ships has_/drop_elevated_privileges" ;;
    35e3bbd8) echo "drop — sync of common.h shapes with upstream PR #5009" ;;
    2f164a70) echo "drop — kwin_display_names()/kwin_display() already in upstream common.h" ;;
    5601b6d6) echo "drop — upstream builds vulkan_encode.cpp; no include guard needed" ;;
    e1d0ff2b) echo "drop — framerateX100 + DMA-BUF EGL loading exist upstream" ;;
    12a03e67) echo "drop — PROJECT_FQDN fallback for the fork's own CMake" ;;
    # --- drop: workarounds for the fork's Windows-shaped core / AlkaidLab CMake ---
    592bc3f5) echo "drop — restores packaging templates the fork's CMake referenced" ;;
    3b215f3e) echo "drop — tray_linux.c→.cpp rename in the fork's cmake" ;;
    da9e1c34) echo "drop — cmake source-list cleanup (inputtino glob)" ;;
    4e9305d6) echo "drop — display_device/VDD stubs + include_directories arg order" ;;
    bea553d9) echo "drop — NVENC SDK headers / boost regex includes in the fork's core" ;;
    52033b56|8eb89ae6) echo "drop — repairs the fork's 2024-shaped cuda.cu against AlkaidLab's color_vectors" ;;
    69338ef4) echo "drop — libavutil/pixdesc.h include (2024 vaapi.cpp shape)" ;;
    6eac1ef8) echo "drop — settings_t::apply_config 3-arg stub (AlkaidLab signature)" ;;
    61382c26) echo "drop — Windows-only settings_t/adapter_names stubs" ;;
    45017b7b) echo "drop — ZakoVDD (vdd_utils/vdd_ioctl) Linux stubs + session listener" ;;
    25b1a1ac) echo "drop — platf:: qualification of mem_type_e in AlkaidLab's display_device" ;;
    # --- assess against the upstream shape before porting ---
    d9216c4d) echo "assess — one-shot EGL DMA-BUF extension loading (upstream graphics.cpp reworked)" ;;
    f6f0cb42) echo "assess — n_dmabuf_infos initialisation (may be upstream code shape only)" ;;
    35cee1de) echo "assess — wrapper-path matching for KWin permission files (KWin side can never match; the KWIN_WAYLAND_NO_PERMISSION_CHECKS env is the working path)" ;;
    # --- re-apply: the fork's own feature/marque (hard-won, must survive the re-fork) ---
    9a259d66) echo "**re-apply** — probe kwin before kms in auto mode (upstream verifies kms first)" ;;
    33051b67) echo "**re-apply** — EFFECTIVE-only cap probe for the kwin display list (upstream's has_elevated_privileges(false) also matches PERMITTED)" ;;
    f13f6247) echo "**re-apply** — keep CAP_PERMITTED when shedding only EFFECTIVE caps (upstream clears both)" ;;
    03bbcec6) echo "**re-apply** — re-verify capture sources per session (linger + SDDM boot)" ;;
    4773c127|b4640528|60cf3d8b|855821dd) echo "**re-apply** — client-selectable display list incl. virtual ids" ;;
    386c450e|ec08581f) echo "**re-apply** (adapt) — display enumeration + the /displays endpoint for client validation" ;;
    5a0f2720|a3e9ee74|049a3953) echo "**re-apply** (redesign) — display-intent resolution plumbing on upstream's display_device API" ;;
    bbac656c|c979423d|fdf1cb4d|98b5dfa2|f686ee05) echo "**re-apply** — virtual-id translation + pre-flight validation exemptions" ;;
    8a4dd818|fa203bd3|04e7a1e0|1215ec00) echo "**re-apply** — session env plumbing for the prep hooks" ;;
    9d9666fa|dc103e15) echo "**re-apply** — 20 s wait for the hook-created output" ;;
    c309f758) echo "**re-apply** — create the virtual monitor before the encoder probe" ;;
    b15755b8) echo "**re-apply** — run the hook for the host-config (默认) pick too" ;;
    fa5ab1f4) echo "**re-apply** (upstream shape differs) — kwin/kms source-identity routing" ;;
    4f731542|f1cae3a4) echo "**re-apply** — ambient cap shedding + dumpable markers for the kwin paths" ;;
    *) echo "unclassified — inspect before porting" ;;
  esac
}

{
  cat <<EOF
# Biaogo's Linux patch series — port queue for the re-fork lane

Generated by \`scripts/gen-fork-linux-port-queue.sh\` — do not edit by hand.
Fork branch audited: \`$FORK\` ($(git rev-parse --short "$FORK")). Re-fork base: \`$UP\` ($(git rev-parse --short "$UP")).
Fork point with upstream: \`$BASE\` (2024-08-26).

Every commit below is authored by Biaogo and touches \`src/platform/linux\`,
\`src/platform/common.h\`, \`cmake/compile_definitions/linux.cmake\`, \`src/display_device\`,
\`src/nvhttp/display_control.*\`, \`src/nvhttp_stream_start.cpp\`, \`src/process.cpp\`,
\`src/video.cpp\` or \`cmake/\`. The queue is what has to survive the move to an upstream base.

| commit | date | subject | verdict |
|---|---|---|---|
EOF
  git log --no-merges --reverse --author='Biaogo' --format='%h %ad %s' --date=short \
    "$BASE..$FORK" -- src/platform/linux src/platform/common.h cmake/compile_definitions/linux.cmake \
    src/display_device src/nvhttp/display_control.cpp src/nvhttp/display_control.h \
    src/nvhttp_stream_start.cpp src/process.cpp src/video.cpp cmake/ |
    while read -r c d s; do
      printf '| `%s` | %s | %s | %s |\n' "$c" "$d" "$(echo "$s" | sed 's/|/\\|/g')" "$(classify "$c")"
    done
  echo
  echo "Totals: $(git rev-list --no-merges --count --author='Biaogo' "$BASE..$FORK" -- src/platform/linux src/platform/common.h cmake/compile_definitions/linux.cmake src/display_device src/nvhttp/display_control.cpp src/nvhttp/display_control.h src/nvhttp_stream_start.cpp src/process.cpp src/video.cpp cmake/) commits audited."
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
