#!/usr/bin/env bash
# Extracts AlkaidLab's two Linux-relevant feature commits as re-apply patches for the re-fork lane,
# together with a per-file shape report (does the file exist on the new base? how big is our delta?).
# Source: the fork checkout (FORK_REPO), destination: docs/reapply-alkaid/ in this tree.
set -uo pipefail
cd "$(dirname "$0")/.."
FORK_REPO=${FORK_REPO:-$HOME/Downloads/foundation-sunshine-linux}
OUT=docs/reapply-alkaid
mkdir -p "$OUT"

# commit -> topic name
declare -A TOPICS=(
  [d80144e7]=mic-mixing-929
  [d855af34]=surround-714-510
)

{
  echo "# AlkaidLab Linux features — re-apply patches"
  echo
  echo "Generated by \`scripts/gen-alkaid-feature-patches.sh\` from $FORK_REPO."
  echo "Each \`*.patch\` is the original fork commit; the table lists, per file, whether the file exists"
  echo "on this (upstream-based) tree and how far our tree's own version has drifted from the fork's."
  echo
  echo "## mic-mixing-929 — multi-client microphone mixing (\`src/mic_mixer.*\`)"
  echo
  echo "## surround-714-510 — 7.1.4 / 12-channel surround"
  echo
} > "$OUT/README.md"

for c in d80144e7 d855af34; do
  topic=${TOPICS[$c]}
  git -C "$FORK_REPO" show "$c" > "$OUT/$topic.patch"
  {
    echo "### $topic (\`$c\`)"
    echo
    echo "| file | on this tree | fork delta | note |"
    echo "|---|---|---|---|"
    git -C "$FORK_REPO" show --name-only --format='' "$c" | while read -r f; do
      [ -z "$f" ] && continue
      if [ -e "$f" ]; then here=yes; else here=**no**; fi
      delta=$(git -C "$FORK_REPO" show --numstat --format='' "$c" -- "$f" | awk -F'\t' '{print "+"$1"/-"$2}')
      printf '| `%s` | %s | %s | |\n' "$f" "$here" "${delta:-?}"
    done
    echo
  } >> "$OUT/README.md"
done

echo "wrote $OUT ($(ls "$OUT"/*.patch | wc -l) patches)"
